version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /docker
    schedule:
      interval: daily
    commit-message:
      prefix: fix
    groups:
      first-party:
        patterns:
          - "tai42-*"
