{{- if .Values.serve.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tai.fullname" . }}-serve
  labels:
    {{- include "tai.labels" . | nindent 4 }}
    app.kubernetes.io/component: serve
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tai.fullname" . }}-serve
  minReplicas: {{ .Values.serve.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.serve.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.serve.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.serve.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.serve.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.serve.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
